### ISSUE TITLE
Broken since lithium 0.13.0

### ISSUE THREAD

**Issue by aclare92** [kikugie/stackable-shulkers-fix#1]
Hi, amazing mod, very much needed to fix the carpet rule and stop them stacking in inventories. But I have noticed this no longer works from 0.13.0 of Lithium. When shulkerboxes are passed through hoppers, they stack to X>1, my case stack to 64. Downgrading lithium to 0.12.7 has this mod working again.

Details of setup below;

Minecraft version: Java 1.21
Server version: fabric-server-mc.1.21-loader.0.16.0-launcher.1.0.1
Carpet version: fabric-carpet-1.21-1.4.147+v240613

Any other details, please feel free to reach out.

**Comment by kikugie** [comment]
Use https://modrinth.com/mod/stackable-shulkers-fix/version/1.3
